const $=id=>document.getElementById(id);
const SUPABASE_URL='https://lfdmbkzghnwvsapxypvt.supabase.co';
const KEY='sb_publishable_bRnkA6PA8-v073nrw9zxiQ_8rVGiOn1';
const SESSION='movida-geiger-session',ATTEMPTS='movida-geiger-attempts';

const state={mode:'guided',step:0,powered:false,audio:false,inspected:false,background:null,gross:null,scanStarted:false,scanComplete:false,hotspot:false,confirmed:false,distance:.5,speed:5,scenario:'lab',timer:null};
const scenarios={lab:{background:36,gross:184,label:'Mesón de laboratorio'},nuclear:{background:44,gross:328,label:'Área de medicina nuclear'},waste:{background:29,gross:112,label:'Zona de residuos radiactivos'}};
const steps=[
 {title:'Inspecciona el sistema',text:'Comprueba carcasa, cable, conector y la delicada ventana de la sonda; luego registra la inspección.',why:'una ventana dañada o contaminada invalida la medición.',target:'probeTarget',action:'Inspección completada',done:()=>state.inspected,run:()=>{state.inspected=true;toast('Inspección registrada: equipo íntegro');advanceSoon()}},
 {title:'Enciende el instrumento',text:'Pulsa el botón de encendido y espera la comprobación inicial.',why:'el equipo debe estabilizarse antes de medir.',target:'powerBtn',action:'Encender equipo',done:()=>state.powered,run:()=>togglePower(true)},
 {title:'Activa la respuesta audible',text:'Activa el audio para reconocer cambios pequeños mientras barres.',why:'los pulsos ayudan a localizar un incremento sin dejar de mirar la superficie.',target:'audioBtn',action:'Activar audio',done:()=>state.audio,run:()=>toggleAudio(true)},
 {title:'Mide el fondo',text:'Obtén un conteo de fondo de 60 segundos, alejado del punto sospechoso.',why:'la lectura bruta incluye radiación ambiental; el resultado útil es el neto.',target:'backgroundBtn',action:'Medir fondo 60 s',done:()=>state.background!==null,run:measureBackground},
 {title:'Ajusta la geometría',text:'Coloca la ventana paralela a 0,3–0,6 cm de la superficie, sin tocarla.',why:'la eficiencia cambia con la distancia y el contacto puede dañar o contaminar la mica.',target:'distance',action:'Usar distancia correcta',done:()=>state.distance>=.3&&state.distance<=.6,run:()=>{$('distance').value=.5;setDistance(.5);advanceSoon()}},
 {title:'Prepara el barrido',text:'Usa aproximadamente un ancho de sonda por segundo: entre 3 y 6 cm/s en este ejercicio.',why:'si avanzas muy rápido, el detector permanece poco tiempo sobre una zona activa.',target:'scanSpeed',action:'Ajustar a 5 cm/s',done:()=>state.speed>=3&&state.speed<=6,run:()=>{$('scanSpeed').value=5;setSpeed(5);advanceSoon()}},
 {title:'Barre toda la superficie',text:'Inicia pasadas paralelas y solapadas. Escucha el cambio de pulsos.',why:'un recorrido ordenado reduce zonas omitidas y permite encontrar puntos elevados.',target:'startScan',action:'Iniciar barrido',done:()=>state.scanComplete,run:startScanning},
 {title:'Confirma el punto',text:'Detén la sonda sobre la máxima respuesta y realiza un conteo fijo de 30 segundos.',why:'el barrido localiza; la medición estacionaria produce el dato que se interpreta.',target:'confirmBtn',action:'Confirmar 30 s',done:()=>state.confirmed,run:confirmHotspot},
 {title:'Interpreta el resultado',text:'Compara la tasa neta con el umbral de decisión y revisa el límite de detección.',why:'estar sobre el fondo no basta; la decisión debe considerar la variabilidad del conteo.',target:'verdict',action:'Revisar interpretación',done:()=>state.confirmed,run:()=>advanceSoon()},
 {title:'Cierra y registra',text:'Documenta fondo, tiempo, distancia, velocidad, resultado y condiciones del escenario.',why:'sin trazabilidad no puede defenderse una conclusión de medición.',target:'verdict',action:'Finalizar práctica',done:()=>state.confirmed,run:()=>{toast('Práctica completada correctamente');renderGuide()}}
];

function setLogin(text){$('loginMessage').textContent=text}
function openApp(member,persist=true){const name=[member?.nombres,member?.apellidos].filter(Boolean).join(' ')||member?.name||'integrante';const expiresAt=member?.expiresAt||Date.now()+20*60e3;if(persist)sessionStorage.setItem(SESSION,JSON.stringify({name,expiresAt}));$('memberName').textContent=name;$('loginGate').hidden=true;$('appShell').hidden=false;document.body.classList.remove('auth-locked');renderGuide();updateDisplay();setTimeout(()=>logout(true),Math.max(0,expiresAt-Date.now()))}
function logout(expired=false){sessionStorage.removeItem(SESSION);clearInterval(state.timer);location.reload();if(expired)sessionStorage.setItem('movida-session-message','La sesión finalizó por seguridad.')}
async function login(e){e.preventDefault();const cedula=$('memberId').value.replace(/\D/g,''),codigo=$('memberPassword').value.trim();if(!cedula||!codigo){setLogin('Escribe tu cédula y tu clave para continuar.');return}const blocked=JSON.parse(localStorage.getItem(ATTEMPTS)||'{"count":0,"until":0}');if(blocked.until>Date.now()){setLogin('Demasiados intentos. Espera unos minutos.');return}const btn=$('loginSubmit');btn.disabled=true;btn.querySelector('span').textContent='Verificando…';try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/acceso_integrante`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify({p_cedula:cedula,p_codigo:codigo})});if(!r.ok)throw Error(r.status);const p=await r.json(),m=Array.isArray(p)?p[0]:p;if(!m){const count=(blocked.count||0)+1,lock=count>=5;localStorage.setItem(ATTEMPTS,JSON.stringify({count:lock?0:count,until:lock?Date.now()+15*60e3:0}));setLogin(lock?'Cinco intentos fallidos. Acceso pausado por 15 minutos.':`Datos no validados. Revisa cédula y clave; quedan ${5-count} intentos.`);return}localStorage.removeItem(ATTEMPTS);openApp(m);toast('Acceso validado')}catch(err){console.error(err);setLogin('El servicio de acceso no está disponible. Intenta nuevamente en unos minutos.')}finally{btn.disabled=false;btn.querySelector('span').textContent='Abrir simulador'}}

function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2800)}
function randomAround(value,spread=5){return Math.max(0,Math.round(value+(Math.random()-.5)*spread*2))}
function updateDisplay(value){const reading=value??(state.powered?(state.background??randomAround(scenarios[state.scenario].background,2)):null);$('meter').classList.toggle('on',state.powered);$('reading').innerHTML=reading===null?'---- <small>CPM</small>':`${reading} <small>CPM</small>`;$('screenMode').textContent=state.powered?(state.scanStarted&&!state.scanComplete?'BARRIDO EN CURSO':state.confirmed?'CONTEO CONFIRMADO':'TASA DE CONTEO'):'EQUIPO APAGADO';$('audioBtn').classList.toggle('active',state.audio);$('audioIcon').style.opacity=state.audio?1:.25;$('scaleBar').style.width=reading===null?'0%':`${Math.min(100,reading/4)}%`}
function togglePower(force){state.powered=force??!state.powered;if(!state.powered){state.audio=false;clearInterval(state.timer)}updateDisplay();renderGuide();if(state.powered){toast('Autocomprobación correcta · batería 92 %');advanceSoon()}}
function toggleAudio(force){if(!state.powered){toast('Primero enciende el instrumento.');pointTo('powerBtn');return}state.audio=force??!state.audio;updateDisplay();renderGuide();toast(state.audio?'Respuesta audible activada':'Respuesta audible desactivada');if(state.audio)advanceSoon()}
function simulateCount(button,duration,onDone,label){if(!state.powered){toast('El equipo está apagado.');pointTo('powerBtn');return}if(button.disabled)return;button.disabled=true;let left=duration;const original=button.textContent;button.textContent=`${label} ${left} s`;clearInterval(state.timer);state.timer=setInterval(()=>{left-=5;button.textContent=`${label} ${Math.max(0,left)} s`;if(left<=0){clearInterval(state.timer);button.disabled=false;button.textContent=original;onDone()}},180)}
function measureBackground(){simulateCount($('backgroundBtn'),60,()=>{state.background=randomAround(scenarios[state.scenario].background,3);$('backgroundResult').textContent=state.background;updateDisplay(state.background);renderGuide();toast(`Fondo registrado: ${state.background} CPM`);advanceSoon()},'Midiendo')}
function setDistance(value){state.distance=Number(value);$('distanceValue').textContent=`${state.distance.toFixed(1).replace('.',',')} cm`;renderGuide();if(state.distance===0)toast('No apoyes la ventana sobre la superficie.');else if(state.distance>.6)toast('Acerca la sonda: esta distancia reduce la respuesta.')}
function setSpeed(value){state.speed=Number(value);$('speedValue').textContent=`${state.speed} cm/s`;renderGuide();if(state.speed>6)toast('Demasiado rápido: podrías pasar sobre un punto sin reconocerlo.')}
function startScanning(){if(!state.powered||!state.audio||state.background===null){toast(!state.powered?'Primero enciende el equipo.':!state.audio?'Activa el audio antes de barrer.':'Primero mide el fondo.');return}if(state.distance<.3||state.distance>.6){toast(state.distance<.3?'Evita el contacto con la superficie.':'Mantén la sonda entre 0,3 y 0,6 cm.');pointTo('distance');return}if(state.speed<3||state.speed>6){toast('Ajusta la velocidad entre 3 y 6 cm/s.');pointTo('scanSpeed');return}if(state.scanStarted&&!state.scanComplete)return;state.scanStarted=true;state.scanComplete=false;state.hotspot=false;$('startScan').disabled=true;$('scanState').textContent='Barrido en curso';const area=$('scanArea'),cursor=$('probeCursor');let tick=0;const rows=4,maxX=area.clientWidth-66,maxY=area.clientHeight-78;clearInterval(state.timer);state.timer=setInterval(()=>{tick++;const progress=Math.min(1,tick/80),row=Math.min(rows-1,Math.floor(progress*rows)),rowProgress=(progress*rows)-row;const x=(row%2?1-rowProgress:rowProgress)*maxX,y=12+row*(maxY/(rows-1));cursor.style.left=`${x}px`;cursor.style.top=`${y}px`;const hot=progress>.58&&progress<.72;cursor.classList.toggle('hot',hot);if(hot){state.hotspot=true;const count=randomAround(scenarios[state.scenario].gross,15);updateDisplay(count);$('scanState').textContent='Incremento localizado';if(state.audio)clickSound()}else updateDisplay(randomAround(scenarios[state.scenario].background,5));if(progress>=1){clearInterval(state.timer);state.scanComplete=true;$('startScan').disabled=false;$('startScan').textContent='Repetir barrido';$('scanState').textContent='Punto marcado · confirma en fijo';renderGuide();toast('Incremento localizado. Ahora confirma el punto.');advanceSoon()}},55)}
function clickSound(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=950;gain.gain.value=.035;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.025)}catch{}}
function confirmHotspot(){if(!state.scanComplete||!state.hotspot){toast('Primero completa el barrido y localiza el incremento.');pointTo('startScan');return}simulateCount($('confirmBtn'),30,()=>{state.gross=randomAround(scenarios[state.scenario].gross,7);state.confirmed=true;$('grossResult').textContent=state.gross;calculateResults();updateDisplay(state.gross);renderGuide();toast('Conteo estacionario completado');advanceSoon()},'Contando')}
function calculateResults(){const b=state.background,g=state.gross,tb=60,tg=30;const net=g-b;const ub=Math.sqrt(b/(tb/60))/Math.sqrt(tb/60);const ug=Math.sqrt(g/(tg/60))/Math.sqrt(tg/60);const uNet=Math.sqrt(ug**2+ub**2);const decision=1.645*Math.sqrt((b*60/tg)+(b*60/tb));const detection=decision+1.645*Math.sqrt(Math.max(1,b+detectionSeed(decision,b)));const low=Math.max(0,net-1.96*uNet),high=net+1.96*uNet;$('netResult').textContent=`${net.toFixed(1)} CPM`;$('thresholdResult').textContent=`${decision.toFixed(1)} CPM`;$('detectionResult').textContent=`${detection.toFixed(1)} CPM`;$('coverageResult').textContent=`${low.toFixed(0)}–${high.toFixed(0)} CPM`;const v=$('verdict');if(net>decision){v.className='verdict detected';v.innerHTML='<b>Efecto neto detectado</b><span>La tasa neta supera el umbral de decisión. Delimita el área y aplica el procedimiento radiológico autorizado.</span>'}else{v.className='verdict clear';v.innerHTML='<b>No demostrado sobre el fondo</b><span>El resultado no supera el umbral. Esto no demuestra ausencia absoluta de actividad.</span>'}}
function detectionSeed(decision,b){return Math.max(0,decision+b)}

function renderGuide(){const guided=state.mode==='guided';$('guideCard').hidden=!guided;$('coach').hidden=!guided;if(!guided)return;const s=steps[state.step];$('guideCount').textContent=`PASO ${state.step+1} DE ${steps.length}`;$('guideNumber').textContent=String(state.step+1).padStart(2,'0');$('guideTitle').textContent=s.title;$('guideText').textContent=s.text;$('guideWhy').textContent=s.why;$('guideAction').textContent=s.action;$('guideBar').style.width=`${((state.step+1)/steps.length)*100}%`;$('guidePrev').disabled=state.step===0;$('guideNext').disabled=!s.done()||state.step===steps.length-1;$('coachStep').textContent=`SIGUIENTE · PASO ${state.step+1} DE ${steps.length}`;$('coachTitle').textContent=s.title;$('coachHint').textContent=`Te llevaré a: ${s.action.toLowerCase()}`;clearTargets()}
function goStep(delta){const next=Math.max(0,Math.min(steps.length-1,state.step+delta));if(delta>0&&!steps[state.step].done()){toast('Completa la acción indicada antes de avanzar.');pointTo(steps[state.step].target);return}state.step=next;renderGuide();$('guideCard').scrollIntoView({behavior:'smooth',block:'start'})}
function advanceSoon(){if(state.mode!=='guided'||!steps[state.step].done()||state.step===steps.length-1)return;setTimeout(()=>{if(steps[state.step].done())goStep(1)},650)}
function clearTargets(){document.querySelectorAll('.coach-target').forEach(el=>el.classList.remove('coach-target'))}
function pointTo(id){clearTargets();const el=$(id);if(!el)return;el.classList.add('coach-target');el.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>el.classList.remove('coach-target'),4500)}
function setMode(mode){state.mode=mode;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('simulationView').hidden=mode==='concepts';$('conceptsView').hidden=mode!=='concepts';renderGuide();if(mode!=='concepts')window.scrollTo({top:70,behavior:'smooth'})}
function resetScenario(value){clearInterval(state.timer);Object.assign(state,{scenario:value,background:null,gross:null,scanStarted:false,scanComplete:false,hotspot:false,confirmed:false});$('backgroundResult').textContent='—';$('grossResult').textContent='—';$('netResult').textContent='— CPM';$('thresholdResult').textContent='— CPM';$('detectionResult').textContent='— CPM';$('coverageResult').textContent='—';$('scanState').textContent='Lista para inspección';$('startScan').textContent='Iniciar barrido';$('startScan').disabled=false;$('verdict').className='verdict neutral';$('verdict').innerHTML='<b>Aún sin resultado</b><span>Completa el fondo, el barrido y la confirmación.</span>';updateDisplay();toast(`Escenario cargado: ${scenarios[value].label}`)}

$('loginForm').addEventListener('submit',login);$('togglePassword').addEventListener('click',()=>{const i=$('memberPassword'),show=i.type==='password';i.type=show?'text':'password';$('togglePassword').textContent=show?'Ocultar':'Mostrar'});$('logoutBtn').addEventListener('click',()=>logout());
document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('powerBtn').addEventListener('click',()=>togglePower());$('audioBtn').addEventListener('click',()=>toggleAudio());$('backgroundBtn').addEventListener('click',measureBackground);$('distance').addEventListener('input',e=>setDistance(e.target.value));$('scanSpeed').addEventListener('input',e=>setSpeed(e.target.value));$('startScan').addEventListener('click',startScanning);$('confirmBtn').addEventListener('click',confirmHotspot);$('scenario').addEventListener('change',e=>resetScenario(e.target.value));$('guideAction').addEventListener('click',()=>steps[state.step].run());$('guidePrev').addEventListener('click',()=>goStep(-1));$('guideNext').addEventListener('click',()=>goStep(1));$('coachShow').addEventListener('click',()=>pointTo(steps[state.step].target));$('modeBtn').addEventListener('click',()=>toast('CPM es la unidad adecuada para el barrido superficial.'));$('countBtn').addEventListener('click',confirmHotspot);
const saved=JSON.parse(sessionStorage.getItem(SESSION)||'null');if(saved?.expiresAt>Date.now())openApp(saved,false);else{sessionStorage.removeItem(SESSION);const msg=sessionStorage.getItem('movida-session-message');if(msg){setLogin(msg);sessionStorage.removeItem('movida-session-message')}}
